export const AboutAppActionTypes = {
  SET_ABOUT_APP: "SET_ABOUT_APP",
  SET_CENTER: "SET_CENTER",
  SET_ZOOM: "SET_ZOOM",
  SET_LEFT_PANEL: "SET_LEFT_PANEL",
  TOGGLE_LEFT_PANEL: "TOGGLE_LEFT_PANEL"
}