export const AnalyitcsPanelActiontypes = {
  SET_ANALYTICS_PANEL: "SET_ANALYTICS_PANEL",
  UPDATA_ANALYTICS_PANEL_CATEGORY_CHECKED: "UPDATA_ANALYTICS_PANEL_CATEGORY_CHECKED",
  UPDATE_ANALYTICS_PANEL_CHECKED: "UPDATE_ANALYTICS_PANEL_CHECKED",
  SET_ANALYTICS_TODO: "SET_ANALYTICS_TODO",
  SET_ANALYSIS_DATA: "SET_ANALYSIS_DATA",
  UPDATE_ANALYSIS_DATA_SHOW: "UPDATE_ANALYSIS_DATA_SHOW",
  ADD_ANALYTICS_TODO: "ADD_ANALYTICS_TODO",
  UPDATE_ANALYTICS_TODO: "UPDATE_ANALYTICS_TODO",
  DELETE_ANALYTICS_TODO: "DELETE_ANALYTICS_TODO",
}