export const LivedataActiontypes ={
    SET_LIVEDATA: "SET_LIVEDATA",
    UPDATA_LIVEDATA_CHECKED: "UPDATA_LIVEDATA_CHECKED",
    SET_LIVEDATA_SOURCES: "SET_LIVEDATA_SOURCES",
    SET_LIVEDATA_SOURCE_CHECKED: "SET_LIVEDATA_SOURCE_CHECKED"
   }